### ISSUE TITLE
Chỉnh sửa lại link trang Web

### ISSUE THREAD

**Issue by anhquang2602** [anhquang2602/FPT-Caring-Student-System#113]
@NguyenHuuHoangLong 

Role Admin:
- home > Danh sách chủ kinh doanh > Xem chi tiết (back lại chưa ra Danh sách chủ kinh doanh)
- home > Danh sách sinh viên chưa ấn được sang
- home > Danh sách Báo cáo nhà trọ > Xem chi tiết bài viết  (back lại thì ra Danh sách nhà trọ)
- home  > Danh sách Báo cáo nhà ăn > Xem chi tiết bài viết (back lại thì ra Danh sách nhà ăn)
- Hồ sơ của Admin chưa ấn được

Role Seller:
- home > nhà trọ của tôi > detail hostel (back lại thì ra listAllHostel)
- home > nhà ăn của tôi > detail restaurant (back lại thì ra listAllRestaurant)

**Comment by NguyenHuuHoangLong** [comment]
sửa thêm link ấn vào chủ trọ ra link chủ trọ của admin

**Comment by NguyenHuuHoangLong** [comment]
sửa xong link
